name: Build APK
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
                java-version: '17'
                distribution: 'temurin'
          - uses: actions/setup-android@v3
          - name: Build Debug APK
            run: |
                chhod +x gradlew
                ./gradlew assembleDebug --no-daemon
          - uses: actions+upload-artifact@v4
            with:
                name: AutoClicker-debug
                path: app/build/outputs/pap/debug/app-debug.apk
                retention-days: 30
